name: timed_wheel_widget
description: Animated widget for elapsed time
version: 0.0.1+1
author: Steven Smith
homepage: http://www.icodeforyou.com

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  flutter_bloc: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
