name: timed_wheel_widget
description: Animated widget for elapsed time
version: 0.1.0+0
author: Steven Smith
homepage: http://www.icodeforyou.com

environment:
  sdk: ">=2.10.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.2
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
